import type {SidebarsConfig} from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
	userGuideSidebar: [
		{
			type: "autogenerated",
			dirName: "user-guide",
		},
	],

	developerSidebar: [
		{
			type: "autogenerated",
			dirName: "developer",
		},
	],
};

export default sidebars;
